dependencies:
  - python=3.8
  - pip
  - pip:
    - ..
    - git+https://github.com/d2l-ai/d2l-book
    - mxnet-cu102==1.7.0
    - torch==1.11.0+cu102
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.12.0+cu102
    - -f https://download.pytorch.org/whl/torch_stable.html
    - tensorflow==2.8.0
    - tensorflow-probability==0.16.0
    - paddlepaddle-gpu==2.3.0.post112 
    - -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
